// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqUl42-pc9J4jTHaTwz9nam3kRPYuRtf4',
    appId: '1:4103511628:web:adac45cf1d320543999ee9',
    messagingSenderId: '4103511628',
    projectId: 'jobber-71b8c',
    authDomain: 'jobber-71b8c.firebaseapp.com',
    storageBucket: 'jobber-71b8c.firebasestorage.app',
    measurementId: 'G-36EEXW6YN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs4Kn8Wl96W_At_2-pK5zcB1j55UuNGaU',
    appId: '1:220701742919:android:7f18e21eb9e07fde82de62',
    messagingSenderId: '220701742919',
    projectId: 'expense-tracker-41009',
    storageBucket: 'expense-tracker-41009.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_UFmtyTghBbLW6OjfiUorGKvW9eoLcWQ',
    appId: '1:220701742919:ios:56c13917e7c548d082de62',
    messagingSenderId: '220701742919',
    projectId: 'expense-tracker-41009',
    storageBucket: 'expense-tracker-41009.firebasestorage.app',
    iosBundleId: 'com.example.ppscPreparation',
  );
}
